---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:
  vars:
    gateway: # Ip Address of Gateway
    netmask: # Network Mask of Subnet
    dns: # Ip Address to DNS Server
    root_password: #"password"
    timezone: #"America/Chicago"
    kick_media: # rhel, centos, or atomic
    iso_pth: # Path to iso /root/rhel-atomic-installer-7.5.0-1.x86_64.iso
    default_boot_drive: # sda
  children:
    nodes:
      children:
        servers:
          hosts:
            rockserver1.lan:
              ip: #192.168.122.10
              mac: #00:50:56:2C:4E:E0
              boot_drive: #sda