---
kick_cfg: ks.cfg
tftp_dir: /var/lib/tftpboot
web_root: /var/www/html

coreos_version: 1688.5.3

install_group: root
rocknsm_dir: /opt
rockoffline_dir: "{{ web_root }}/offlinerepo"
install_dir: /opt/rock
sysctl_file: /etc/sysctl.d/rock.conf
fqdn: default.svc.cluster.local

# Elasticsearch
elastic_ver: '6.2.2'
es_cluster_name: rock
elastic_fqdn: "elasticsearch.{{ fqdn }}"
elastic_port: 9200

# Kibana
kibana_fqdn: "kibana.{{ fqdn }}"

# If you have licensing for x-pack set variable to true.
xpack_license: 'true'

# Kafka
kafka_fqdn: "kafka.{{ fqdn }}"
kafka_port: 9092
kafka_retention: 168

rock_hostname: "ansiblecontroller"
harbor_ver: '1.4.0'

additional_repo_info:
  kube:
    name: "kubernetes"
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    gpgkeyurl: "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
    gpgkeyname: "yum-key.gpg"
    description: "kubernetes repo"
    # Required because kube public repo uses relative path so this is a hack to fix it
    download_path: "{{ rockoffline_dir }}/tmp"
  rocknsm:
    name: "rocknsm"
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/epel-7-$basearch/"
    gpgkeyurl: "https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/pubkey.gpg"
    gpgkeyname: "pubkey.gpg"
    description: "rocknsm repo"
    download_path: "{{ rockoffline_dir }}"
  epel:
    name: "epel"
    baseurl: "http://download.fedoraproject.org/pub/epel/7/$basearch"
    gpgkeyurl: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    gpgkeyname: "RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    description: "epel repo"
    download_path: "{{ rockoffline_dir }}"
  ceph_base:
    name: "ceph_base"
    baseurl: "https://download.ceph.com/rpm-luminous/el7/$basearch"
    gpgkeyurl: "https://download.ceph.com/keys/release.asc"
    gpgkeyname: "release.asc"
    description: "ceph base repo"
    download_path: "{{ rockoffline_dir }}"
  ceph_noarch:
    name: "ceph_noarch"
    baseurl: "https://download.ceph.com/rpm-luminous/el7/$basearch"
    gpgkeyurl: "https://download.ceph.com/keys/release.asc"
    gpgkeyname: "release.asc"
    description: "ceph base repo"
    download_path: "{{ rockoffline_dir }}"
  ceph_srpms:
    name: "ceph_srpms"
    baseurl: "https://download.ceph.com/rpm-luminous/el7/SRPMS"
    gpgkeyurl: "https://download.ceph.com/keys/release.asc"
    gpgkeyname: "release.asc"
    description: "ceph srpms repo"
    download_path: "{{ rockoffline_dir }}"

bootstrap_package_names:
  - yum-utils
  - createrepo

gpg_keys:
  - "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  - "https://copr-be.cloud.fedoraproject.org/results/@rocknsm/rocknsm-2.1/pubkey.gpg"
  - "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
  - "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

pip_downloads:
  - docker-py
...
