---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:
  vars:
    default_boot_drive: sda
    dnsmasq: true
    dhcp: true    
    dhcp_start: 192.168.122.50   
    dhcp_end: 192.168.122.240
    dhcp_mask: '{{ ansible_default_ipv4.netmask }}'
    dhcp_net: '{{ ansible_default_ipv4.network }}'
    dns: 192.168.122.7
    gateway: 192.168.122.2

    pull_all_repos: false
    pull_centos_repos: false
    pull_rhel_repos: true
    pull_additional_repos: true
    
    # iso_path and kick media need to be changed based on the source iso used.
    iso_pth: /root/rhel-server-7.4-x86_64-dvd.iso
    kick_media: rhel # centos, rhel or atomic
    
    kick_srvr: '{{ ansible_default_ipv4.address }}'    
    netmask: 255.255.255.0    
    root_password: "password"
    timezone: "America/Chicago"
  children:
    nodes:
      children:
        servers:
          hosts:
            rockserver1.lan: 
              ip: 192.168.122.4
              mac: 00:50:56:22:B2:42
              boot_drive: sda
            rockserver2.lan:
              ip: 192.168.122.5
              mac: 00:50:56:39:32:59
              boot_drive: sda            
            rocksensor1.lan:
              ip: 192.168.122.6
              mac: 00:50:56:34:FB:53
              boot_drive: sda
