---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:
  vars:
    default_boot_drive: sda
    dnsmasq: true
    dhcp: true    
    dhcp_start: 192.168.122.50   
    dhcp_end: 192.168.122.240
    dhcp_mask: '{{ ansible_default_ipv4.netmask }}'
    dhcp_net: '{{ ansible_default_ipv4.network }}'
    dns: 192.168.122.7
    gateway: 192.168.122.2

    # iso_path and kick media need to be changed based on the source iso used.
    iso_pth: /root/CentOS-7-x86_64-Minimal-1708.iso
    kick_media: centos # centos, rhel or atomic
    
    kick_srvr: '{{ ansible_default_ipv4.address }}'    
    netmask: 255.255.255.0    
    root_password: "password"
    timezone: "America/Chicago"
  children:
    nodes:
      children:
        servers:
          hosts:
            rockserver1.lan: 
              ip: 192.168.122.4
              mac: 00:0c:29:09:31:67
              boot_drive: sda
            rockserver2.lan: 
              ip: 192.168.122.5
              mac: 00:0C:29:BC:A2:B7
              boot_drive: sda
            rocksensor1.lan:
              ip: 192.168.122.6
              mac: 00:0c:29:ae:48:c9
              boot_drive: sda
            rocksensor2.lan:
              ip: 192.168.122.9
              mac: 00:0c:29:21:59:f5
              boot_drive: sda
            rockserver3.lan:
              ip: 192.168.122.10
              mac: 00:50:56:29:0A:6E
              boot_drive: sda