---
# handlers file for roles/dnsmasq

- name: NetworkManager Services
  service:
    name: NetworkManager
    state: restarted
  listen: "Restart Network Services"

- name: Network Services
  service:
    name: network
    state: restarted
  listen: "Restart Network Services"

- name: DNS Services
  service:
    name: dnsmasq
    state: restarted
  listen: "Restart Network Services"

