---
- name: "Install httpd so this repo can be published"
  yum:
    name: httpd
    state: present

- name: "Open up port 80 to allow access"
  firewalld: 
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: "Start httpd"
  service: 
    name: httpd
    state: started
    enabled: yes