---
- name: "Download all other direct download files into local repository, including dependencies"
  get_url:
    url: "{{ item }}" 
    dest: "{{ rockoffline_dir }}/misc"
  with_items:
    - "{{ direct_download_package_names }}"