---
- name: Additional Repos
  block:
    - name: "Check if EPEL repo is already configured"
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result

    - name: "Install EPEL release"
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      register: result
      when: not epel_repofile_result.stat.exists

    - name: "Setup ROCK NSM repo"
      yum_repository:
        baseurl: "{{ rocknsm_baseurl }}"
        description: "ROCK NSM repository for devel"
        gpgcheck: false
        name: rocknsm

    - name: "Setup Kubernetes repo"
      yum_repository:
        baseurl: "{{ kube_baseurl }}"
        description: "Kubernetes YUM repo"
        gpgcheck: false
        name: kubernetes

    - name: "Mirror Additional repositories"
      shell: "reposync --repoid={{ item }} --download_path={{ rockoffline_dir }} --download-metadata --downloadcomps"
      with_items:
        - "{{ additional_repos }}"  

  when: (pull_all_repos is defined and pull_all_repos) 
    or (pull_additional_repos is defined and pull_additional_repos)