---

- name: set repo list
  set_fact:
    repos: []

- name: setup repo list
  set_fact:
    repos: "{{ repos }} + [ 'misc' ]" 

- name: setup repo list
  set_fact:
    repos: "{{ repos }} + [ '{{ item }}' ]" 
  when: (pull_all_repos is defined and pull_all_repos) 
    or (pull_rhel_repos is defined and pull_rhel_repos) 
  with_items: "{{ rhel_repos }}"

- name: setup repo list
  set_fact:
    repos: "{{ repos }} + [ '{{ item }}' ]" 
  when: (pull_all_repos is defined and pull_all_repos) 
    or (pull_centos_repos is defined and pull_centos_repos) 
  with_items: 
  - "{{ centos_repos }}"

- name: setup repo list
  set_fact:
    repos: "{{ repos }} + [ '{{ item.value.name }}' ]" 
  when: (pull_all_repos is defined and pull_all_repos) 
    or (pull_additional_repos is defined and pull_additional_repos) 
  loop: "{{ lookup('dict', additional_repo_info) }}"

- name: Remove Repodata
  file:
    path: "{{ rockoffline_dir }}/repodata"
    state: absent

- name: Setup RepoData
  include_tasks: include_repo.yml repo="{{ item }}"
  with_items: "{{ repos }}"

- name: get list of directories with wrong permissions
  shell: |
    find {{ rockoffline_dir }} -type d -not -perm 755
  register: dir_list

- name: Update directory permissions
  file:
    path: "{{ item }}"   
    mode: 0755
    setype: httpd_sys_content_t
    owner: root
    group: root
  with_items: "{{ dir_list.stdout }}"
  when: dir_list.stdout != ""

- name: fix files with wrong permissions
  shell: |
    find {{ rockoffline_dir }} -type f -not -perm 644 -exec chmod 644 {} \;
  register: file_list

- name: restorecon offlinerepo
  shell: |
    restorecon -Rv {{ rockoffline_dir }}