#######################################################
################## Predownload Repos ##################
#######################################################
---
- import_tasks: 00_httpd.yml
- import_tasks: 05_setup.yml
- import_tasks: 10_pip.yml
- import_tasks: 15_direct.yml
  tags: direct
- import_tasks: 20_centos.yml
- import_tasks: 25_rhel.yml
- import_tasks: 30_additional.yml
  tags: additional
- import_tasks: 35_createrepo.yml
  tags: createrepo
...
