---
- name: Configure dns server
  block:
    - name: Install packages
      yum:
        name: "dnsmasq"
        state: latest
    
    - name: Create /etc/hosts
      template:
        src: "hosts.j2"
        dest: "/etc/hosts"
        owner: root
        group: root
        mode: 0644
      register: dnsmasq_result
      notify: "Restart Network Services"
    
    - name: DNS Services
      service:
        name: "dnsmasq"
        state: started
        enabled: yes
      when: dnsmasq_result.changed

    - name: DNS Firewall
      firewalld:
        service: dns
        state: enabled
        immediate: yes
        permanent: yes        
  when: dnsmasq is defined and dnsmasq


