# Configure tftp service
---
- name: Configure TFTP
  block:
    - name: Install {{ tftp_pkgs }}
      yum:
        name: "{{ tftp_pkgs }}"
        state: latest

    - name: Create pxelinux.cfg
      file:
        state: directory
        owner: root
        group: root
        mode: 0755
        setype: cobbler_var_lib_t
        path: "{{ tftp_dir }}/pxelinux.cfg"

    - name: Place pxe files
      copy:
        src: "{{ item }}"
        dest: "{{ tftp_dir }}"
        setype: cobbler_var_lib_t
      register: tftp
      with_items:
        - "{{ tftp_pxe }}"

    - name: Default pxe menu
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
        setype: "{{ item.setype }}"
      register: tftp
      with_items:
      #- { src: 'default.j2', dest: '{{ tftp_dir }}/pxelinux.cfg/default', setype: 'cobbler_var_lib_t'}
      - { src: 'tftp.j2', dest: '/etc/xinetd.d/tftp', setype: 'etc_t'}

    - name: TFTP Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
      - xinetd
      - tftp
      when: tftp.changed

    - name: TFTP Firewall
      firewalld:
        service: tftp
        state: enabled
        immediate: yes
        permanent: yes