---
- name: Download {{ kick_media }} ISO
  get_url:
    url: "{{ item }}" 
    dest: "{{ iso_pth }}"
  with_items:
    - "{{ iso_url }}"
  when: iso_url != ""

- name: Mount content to {{ mnt_pth }}
  mount:
    fstype: iso9660
    state: mounted
    opts: loop
    path: "{{ mnt_pth }}"
    src: "{{ iso_pth }}"
  when:
    - mnt_pth != ""  
    - iso_pth != ""  
  register: mounted

- name: Create repo from local media
  yum_repository:
    baseurl: "file://{{ mnt_pth }}"
    description: Local Media Repo
    name: "{{ reponame }}"
    enabled: yes
    gpgcheck: no
  when: mounted is succeeded

- name: Install extra_packages
  yum:
    name: "{{ xtras }}"
    state: latest