---
- name: coreos block
  block:
    - name: Create directory coreos version dir
      file:
        state: directory
        owner: root
        group: root
        mode: 0755
        setype: httpd_sys_content_t
        path: "{{ web_root }}/{{ kick_media }}/{{ coreos_version }}"

    - name: "Download coreos files"
      get_url:
        url: "{{ item }}" 
        dest: "{{ web_root }}/{{ kick_media }}/{{ coreos_version }}"
      with_items:
        - "{{ coreos_deps }}"
  when: "'coreos' in kick_media"