---
- import_tasks: 99_repo.yml
- import_tasks: 99_httpd.yml
- import_tasks: 10_tftp.yml
- import_tasks: 15_dhcp.yml
- import_tasks: coreos.yml
- import_tasks: 99_cleanup.yml
  when: cleanup is defined and cleanup


