---
- name: atomic block
  block:
    - name: Create atomic ks for each server
      template:
        src: "atomic.cfg.j2"
        dest: "{{ ks_template_dir }}/{{ item }}.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      with_items:
      - "{{ groups['servers'] }}"
      when: "'atomic' in kick_media"
    