---
- name: "{{ kick_media }} block"
  block:
    - name: Make default bios {{ kick_media }} {{ kick_cfg }} avail
      template:
        src: ks.cfg.j2
        dest: "{{ ks_template_dir }}/ks.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      vars:
        uefi: false
        
    - name: Make default uefi {{ kick_media }} {{ kick_cfg }} avail
      template:
        src: ks.cfg.j2
        dest: "{{ ks_template_dir }}/ks.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      vars:
        uefi: true

    - name: Create {{ kick_media }} bios ks for each server
      template:
        src: "ks.cfg.j2"
        dest: "{{ ks_template_dir }}/{{ item }}.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      with_items:
      - "{{ groups['servers'] }}"
      vars:
        uefi: false

    - name: Create {{ kick_media }} uefi ks for each server
      template:
        src: "ks.cfg.j2"
        dest: "{{ ks_template_dir }}/uefi/{{ item }}.cfg"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      with_items:
      - "{{ groups['servers'] }}"
      vars:
        uefi: true

    - name: Default {{ kick_media }} PXE Menus
      template:
        src: "default.j2"
        dest: "{{ tftp_dir }}/pxelinux.cfg/default"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp

    - name: UEFI {{ kick_media }} PXE Menus
      template:
        src: "grub.cfg.j2"
        dest: "{{ tftp_dir }}/uefi/grub.cfg"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp

    - name: Create {{ kick_media }} bios pxe menu for each server
      template:
        src: "default.j2"
        dest: "{{ tftp_dir }}/pxelinux.cfg/01-{{ hostvars[item].mac | regex_replace(':', '-') | lower }}"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp
      with_items:
      - "{{ groups['servers'] }}"

    - name: Create {{ kick_media }} uefi pxe menu for each server
      template:
        src: "grub.cfg.j2"
        dest: "{{ tftp_dir }}/uefi/grub.cfg-01-{{ hostvars[item].mac | regex_replace(':', '-') | lower }}-"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp
      with_items:
      - "{{ groups['servers'] }}"
  when: "'rhel' in kick_media or 'centos' in kick_media"

