---
- name: coreos block
  block:
    - name: Create coreos config for each server
      template:
        src: "coreos-config.json.j2"
        dest: "{{ ks_template_dir }}/coreos-{{ item }}.json"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
      with_items:
      - "{{ groups['servers'] }}"     
    - name: Create default coreos config
      template:
        src: "coreos-config.json.j2"
        dest: "{{ ks_template_dir }}/coreos-config.json"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
    - name: coreos install config
      template:
        src: "coreos-installer.json.j2"
        dest: "{{ ks_template_dir }}/coreos-installer.json"
        owner: root
        group: root
        mode: 0644
        setype: httpd_sys_content_t
    - name: coreos PXE Menus
      template:
        src: "coreos-default.j2"
        dest: "{{ tftp_dir }}/pxelinux.cfg/default"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp
    - name: Create bios pxe menu for each server
      template:
        src: "coreos-default.j2"
        dest: "{{ tftp_dir }}/pxelinux.cfg/01-{{ hostvars[item].mac | regex_replace(':', '-') | lower }}"
        owner: root
        group: root
        mode: 0644
        setype: "cobbler_var_lib_t"
      register: tftp
      with_items:
      - "{{ groups['servers'] }}"
  when: "'coreos' in kick_media"