---

- name: Generate RootPw
  command: "openssl passwd -1 {{ root_password }}"
  register: rootpw

- name: Kick template dir
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    setype: httpd_sys_content_t
    path: "{{ ks_template_dir }}"

- name: Make {{ kick_cfg }} avail
  template:
    src: ks.cfg.j2
    dest: "{{ ks_template_dir }}/ks.cfg"
    owner: root
    group: root
    mode: 0644
    setype: httpd_sys_content_t

- name: Create ks for each server
  template:
    src: "ks.cfg.j2"
    dest: "{{ ks_template_dir }}/{{ item }}.cfg"
    owner: root
    group: root
    mode: 0644
    setype: httpd_sys_content_t
  with_items:
  - "{{ groups['servers'] }}"
  when: "'atomic' not in kick_media"

- name: Create atomic ks for each server
  template:
    src: "atomic.cfg.j2"
    dest: "{{ ks_template_dir }}/{{ item }}.cfg"
    owner: root
    group: root
    mode: 0644
    setype: httpd_sys_content_t
  with_items:
  - "{{ groups['servers'] }}"
  when: "'atomic' in kick_media"

- name: Default pxe menu
  template:
    src: "default.j2"
    dest: "{{ tftp_dir }}/pxelinux.cfg/default"
    owner: root
    group: root
    mode: 0644
    setype: "cobbler_var_lib_t"
  register: tftp

- debug:
    msg: "{{ hostvars[item].mac }}"
  with_items:
  - "{{ groups['servers'] }}"

- name: Create pxe menu for each server
  template:
    src: "default.j2"
    dest: "{{ tftp_dir }}/pxelinux.cfg/01-{{ hostvars[item].mac | regex_replace(':', '-') | lower }}"
    owner: root
    group: root
    mode: 0644
    setype: "cobbler_var_lib_t"
  register: tftp
  with_items:
  - "{{ groups['servers'] }}"


